newUnits/config/routes.rb
NewUnits::Application.routes.draw do
  resources :units

  root :to => 'units#index'

end

newUnits/app/models/unit.rb
class Unit
  include Mongoid::Document
  field :Fluid, type: String
  field :Group, type: String
  field :SN, type: Integer
  field :chNull, type: Float
  field :chTCR, type: Float
  field :crNull, type: Float
  field :crTCR, type: Float
  field :fullSN, type: String
  field :hyst, type: Float
  field :lin, type: Float
  field :nfsoSet, type: Float
  field :nullSet, type: Float
  field :rhNull, type: Float
  field :rhTCR, type: Float

  def self.search(search)
    if search
      Unit.any_of({Fluid: /#{Regexp.escape(search)}/}, \
        {Group: /#{Regexp.escape(search)}/}, \
        {fullSN: /#{Regexp.escape(search)}/})
    else
      scoped
    end
  end
end

newUnits/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

newUnits/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /units
  # GET /units.json
  def index
    @units = Unit.search(params[:search]).order_by(sort_column + " " + sort_direction).paginate(:per_page => 100, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end


private

  def sort_column
    #Unit.column_names.include?(params[:sort]) ? params[:sort] : "SN"
    params[:sort] = params[:sort] || "SN"
  end

  def sort_direction
    #%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    params[:direction] = params[:direction] || "asc"
  end
end

newUnits/app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

newUnits/app/helpers/units_helper.rb
module UnitsHelper
end

newUnits/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "unitMongoRecord" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="main_content">
      <%= yield %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

newUnits/app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fluid %><br />
    <%= f.text_field :Fluid %>
  </div>
  <div class="field">
    <%= f.label :Group %><br />
    <%= f.text_field :Group %>
  </div>
  <div class="field">
    <%= f.label :SN %><br />
    <%= f.number_field :SN %>
  </div>
  <div class="field">
    <%= f.label :chNull %><br />
    <%= f.text_field :chNull %>
  </div>
  <div class="field">
    <%= f.label :chTCR %><br />
    <%= f.text_field :chTCR %>
  </div>
  <div class="field">
    <%= f.label :crNull %><br />
    <%= f.text_field :crNull %>
  </div>
  <div class="field">
    <%= f.label :crTCR %><br />
    <%= f.text_field :crTCR %>
  </div>
  <div class="field">
    <%= f.label :fullSN %><br />
    <%= f.text_field :fullSN %>
  </div>
  <div class="field">
    <%= f.label :hyst %><br />
    <%= f.text_field :hyst %>
  </div>
  <div class="field">
    <%= f.label :lin %><br />
    <%= f.text_field :lin %>
  </div>
  <div class="field">
    <%= f.label :nfsoSet %><br />
    <%= f.text_field :nfsoSet %>
  </div>
  <div class="field">
    <%= f.label :nullSet %><br />
    <%= f.text_field :nullSet %>
  </div>
  <div class="field">
    <%= f.label :rhNull %><br />
    <%= f.text_field :rhNull %>
  </div>
  <div class="field">
    <%= f.label :rhTCR %><br />
    <%= f.text_field :rhTCR %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

newUnits/app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

newUnits/app/views/units/index.html.erb
<h1>Listing Units</h1>

<%= form_tag units_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <p><a href="/units">Reset Search</a></p>
<% end %>
<% sort_direction; sort_column %>
<table class="pretty">
  <tr>
    <th><%= sortable "SN" %> </th>
    <th><%= sortable "fullSN" %> </th>
    <th><%= sortable "Fluid" %> </th>
    <th><%= sortable "Group" %> </th>
    <th><%= sortable "chNull" %> </th>
    <th><%= sortable "chTCR" %> </th>
    <th><%= sortable "crNull" %> </th>
    <th><%= sortable "crTCR" %> </th>
    <th><%= sortable "rhNull" %> </th>
    <th><%= sortable "rhTCR" %> </th>
    <th><%= sortable "hyst" %> </th>
    <th><%= sortable "lin" %> </th>
    <th><%= sortable "nfsoSet" %> </th>
    <th><%= sortable "nullSet" %> </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.SN %></td>
    <td><%= unit.fullSN %></td>
    <td><%= unit.Fluid %></td>
    <td><%= unit.Group %></td>
    <td><%= unit.chNull %></td>
    <td><%= unit.chTCR %></td>
    <td><%= unit.crNull %></td>
    <td><%= unit.crTCR %></td>
    <td><%= unit.rhNull %></td>
    <td><%= unit.rhTCR %></td>
    <td><%= unit.hyst %></td>
    <td><%= unit.lin %></td>
    <td><%= unit.nfsoSet %></td>
    <td><%= unit.nullSet %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @units %>

<br />

<%= link_to 'New Unit', new_unit_path %>

newUnits/app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

newUnits/app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fluid:</b>
  <%= @unit.Fluid %>
</p>

<p>
  <b>Group:</b>
  <%= @unit.Group %>
</p>

<p>
  <b>Sn:</b>
  <%= @unit.SN %>
</p>

<p>
  <b>Chnull:</b>
  <%= @unit.chNull %>
</p>

<p>
  <b>Chtcr:</b>
  <%= @unit.chTCR %>
</p>

<p>
  <b>Crnull:</b>
  <%= @unit.crNull %>
</p>

<p>
  <b>Crtcr:</b>
  <%= @unit.crTCR %>
</p>

<p>
  <b>Fullsn:</b>
  <%= @unit.fullSN %>
</p>

<p>
  <b>Hyst:</b>
  <%= @unit.hyst %>
</p>

<p>
  <b>Lin:</b>
  <%= @unit.lin %>
</p>

<p>
  <b>Nfsoset:</b>
  <%= @unit.nfsoSet %>
</p>

<p>
  <b>Nullset:</b>
  <%= @unit.nullSet %>
</p>

<p>
  <b>Rhnull:</b>
  <%= @unit.rhNull %>
</p>

<p>
  <b>Rhtcr:</b>
  <%= @unit.rhTCR %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>